[package]
name = "first_game"
version = "0.1.0"
authors = ["carter <weinbergcarter@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.5"
bevy_rapier2d = { version = "0.10.2", features = [ "render" ] }
